spring:
  application:
    name: hackathon-be
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8080
