name: Build & Deploy (EC2 - Hackathon)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build & Test
        working-directory: backend/hackathon-be
        run: ./mvnw -B verify

      - name: Locate JAR
        id: jar
        working-directory: backend/hackathon-be
        run: |
          JAR=$(ls target/*.jar | head -n1)
          echo "jar=$JAR" >> $GITHUB_OUTPUT

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Upload JAR & switch symlink
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo mkdir -p ${{ secrets.APP_PATH }}/releases'
          TS=$(date +%Y%m%d-%H%M%S)
          scp -o StrictHostKeyChecking=no "${{ steps.jar.outputs.jar }}" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.APP_PATH }}/releases/hackathon-api-${TS}.jar
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo ln -sf ${{ secrets.APP_PATH }}/releases/hackathon-api-${TS}.jar ${{ secrets.APP_PATH }}/hackathon-api.jar"

      - name: Restart service
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo systemctl restart hackathon && sleep 3 && sudo systemctl is-active --quiet hackathon'
